name: Sync Drive to Photos

on:
  workflow_dispatch:

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run Drive to Photos Sync
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
          PYTHONUNBUFFERED: "1"
        run: python drive_to_photos.py
