name: TeraBox Link Scanner
on:
  workflow_dispatch:

jobs:
  scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install telethon

      - name: Run Scanner
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          MAIN_CHANNEL: ${{ secrets.MAIN_CHANNEL }}
          PYTHONUNBUFFERED: "1"
        run: python terabox_scanner.py
